# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - statefulset.yaml


configMapGenerator:
  - name: minecraft-backup-script
    files:
      - ./shell/backup.sh
      - ./shell/cron-root
      - ./shell/entrypoint.sh
