apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/k8s/minecraft/
